name: Daily Contributions

on:
  schedule:
    - cron: '0 0 * * 1-5'
  workflow_dispatch:

jobs:
  make-contribution:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make daily contribution
        run: |
          echo "* $(date)" >> CONTRIBUTIONS.md

      - name: Commit and Push
        run: |
          git config --local user.email "umerjamshaid481@gmail.com"
          git config --local user.name "Umerjamshaid"
          git add CONTRIBUTIONS.md
          git commit -m "chore: daily activity log $(date +'%Y-%m-%d')"
          git push